#!/usr/bin/env bash
# Configuring the domain zone so that the subdomain 'www' points to the load-balancer IP (lb-01)
# script that will display information about subdomains
# Go to get.tech website, log into your account there-> my account->jump to domain->DNS management->Manage DNS->Add A Record->in the first box shown add www(before .anebue.tech)->second box add IP of lb-01(load balancer)->Add Record->Do the same for lb-01 pointing to IP lb-01, web-01 pointing to IP web-01 and web-02 pointing to IP web-02

configure_domain_name () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  configure_domain_name "$1" "www"
  configure_domain_name "$1" "lb-01"
  configure_domain_name "$1" "web-01"
  configure_domain_name "$1" "web-02"
elif [ "$#" == 2 ]
then
  configure_domain_name "$1" "$2"
fi
