#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page
# The redirection must be a “301 Moved Permanently”
# script containing commands to automatically configure a Ubuntu machine
# to respect above requirements

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
replacement_string="server_name _;\n\trewrite ^\/redirect_me https://www.linkedin.com/feed/ permanent;"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

sudo service nginx restart
