#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header(on web-01 and web-02)
# The name of the custom header must be X-Served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get -y update
sudo apt-get -y install nginx

# Setting up firewall to grant request via port 80
sudo ufw allow 'Nginx HTTP'
sudo mkdir -p /var/www/html

# Changing permissions for easy creation of files in /var/www
sudo chown -R "$USER":"$USER" /var/www
sudo chmod -R 755 /var/www

# Creating index page
echo 'Hello World!' | sudo tee  /var/www/html/index.nginx-debian.html

# Create error 404 webpage
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Configure redirect page(using /redirect_me) and add header to show hostname
replacement_string="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https:\/\/www.linkedin.com\/feed\/ permanent;"
sudo sed -i "s/server_name _;/$replacement_string/" /etc/nginx/sites-enabled/default

# Configure redirect for error 404 page
replacement_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$replacement_string/" /etc/nginx/sites-enabled/default

service nginx restart
